name: Compact display

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" #  run every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Display Achievements
      uses: lowlighter/metrics@latest
      with:
        github_user_name: ${{ github.repository_owner }}
        filename: metrics.plugin.achievements.compact.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_achievements: yes
        plugin_achievements_only: >-
          polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
          scripter, packager, explorer, infographile, manager
        plugin_achievements_display: compact
        plugin_achievements_threshold: X
